// <auto-generated />
namespace ASP.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class poprawkiwmodeluczlonkowstwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poprawkiwmodeluczlonkowstwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201610032341383_poprawki-w-modelu-czlonkowstwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
